services:
  next:
    image: node
    working_dir: /app
    command: sh -c 'npm i && npm run drizzle:push && npm run seed && npm run build && npm run start'
    environment:
      - BETTER_AUTH_SECRET=3SEHlkPdPMsD0s7EkAqAgypTsgigI5SF
      - BETTER_AUTH_URL=http://localhost:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  node_modules:
